services:
  # RabbitMQ service (đã có sẵn image trên Docker Hub)
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"      # Cổng giao tiếp giữa services
      - "15672:15672"    # Cổng giao diện web của RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    image: baoisspro/api-gateway
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  user-service:
    image: baoisspro/user-service
    depends_on:
      - rabbitmq

  auth-service:
    image: baoisspro/auth-service
    depends_on:
      - rabbitmq

  order-service:
      image: baoisspro/order-service
      depends_on:
        - rabbitmq

  policy-service:
      image: baoisspro/policy-service
      depends_on:
        - rabbitmq

  product-service:
      image: baoisspro/product-service
      depends_on:
        - rabbitmq

  review-service:
      image: baoisspro/review-service
      depends_on:
        - rabbitmq
